#!/usr/bin/with-contenv bash

echo '---------------------------'
echo '|  NZBGet theme.park Mod  |'
echo '---------------------------'

APP_FILEPATH='/app/nzbget/webui/index.html'
# Display variables for troubleshooting
echo -e "Variables set:\\n\
'TP_DOMAIN'=${TP_DOMAIN}\\n\
'TP_THEME'=${TP_THEME}\\n"

# Set default
if [[ -z ${TP_DOMAIN} ]]; then
    echo 'No domain set, defaulting to gilbn.github.io'
    TP_DOMAIN='gilbn.github.io'
fi

if [[ -z ${TP_THEME} ]]; then
    echo 'No theme set, defaulting to organizr-dark'
    TP_THEME='organizr-dark'
fi

if [ "${TP_HOTIO}" = true ]; then
    echo 'Changing to Hotio file paths!'
    APP_FILEPATH='/app/webui/index.html'
fi

# Adding stylesheets
if ! grep -q "${TP_DOMAIN}" ${APP_FILEPATH}; then
    echo '---------------------------'
    echo '|  Adding the stylesheet  |'
    echo '---------------------------'
    sed -i "s/<\/head>/<link rel='stylesheet' href='https:\/\/${TP_DOMAIN}\/theme.park\/CSS\/themes\/nzbget\/${TP_THEME}.css'><\/head> /g" ${APP_FILEPATH}
    printf 'Stylesheet set to %s\n' "${TP_THEME}
    "
fi