#!/usr/bin/with-contenv bash

echo '-------------------------'
echo '| Mylar3 theme.park Mod |' 
echo '-------------------------'

APP_FILEPATH='/app/mylar3/data/interfaces/default'
if [ "${TP_HOTIO}" = true ]; then
    echo 'Changing to Hotio file path!'
    APP_FILEPATH='/app/data/interfaces/default'
fi

# Display variables for troubleshooting 
echo -e "Variables set:\\n\
'APP_FILEPATH'=${APP_FILEPATH}\\n\
'TP_HOTIO'=${TP_HOTIO}\\n\
'TP_DOMAIN'=${TP_DOMAIN}\\n\
'TP_THEME'=${TP_THEME}\\n"

# Set default
if [[ -z ${TP_DOMAIN} ]]; then
    echo 'No domain set, defaulting to theme-park.dev'
    TP_DOMAIN='theme-park.dev'
fi

case ${TP_DOMAIN} in
  *"github.io"*)
  echo "Switching to github.io URL style"
    TP_DOMAIN="${TP_DOMAIN}\/theme.park"
    ;;
esac

if [[ -z ${TP_THEME} ]]; then
    echo 'No theme set, defaulting to organizr-dark'
    TP_THEME='organizr-dark'
fi

sed_file(){
	sed -i "s/<\/head>/<link rel='stylesheet' href='https:\/\/${TP_DOMAIN}\/CSS\/themes\/mylar3\/mylar3-base.css'><\/head> /g" $1
    sed -i "s/<\/head>/<link rel='stylesheet' href='https:\/\/${TP_DOMAIN}\/CSS\/variables\/${TP_THEME}.css'><\/head> /g" $1
	printf 'Stylesheet set to %s on %s\n\n' "${TP_THEME}" "$1"
}

# Adding stylesheets
echo '---------------------------------------'
echo '| Adding the stylesheet to html files |'
echo '---------------------------------------'

if ! grep -q "${TP_DOMAIN}" "${APP_FILEPATH}/index.html"; then
    find ${APP_FILEPATH} -type f -iname *.html | while read fname
	do
		sed_file $fname
	done
fi
